allowBuilds:
  "@parcel/watcher": true
  "esbuild": true
  "vue-demi": true

catalogs:
  dev:
    "oxfmt": latest
    "typescript": "7.0.2"
    "@iconify-json/lucide": latest
    "@iconify-json/material-icon-theme": latest
    "@iconify-json/simple-icons": latest
    "@iconify-json/vscode-icons": latest
  vue:
    "vue": "3.5.41"
    "vue-router": "5.2.0"
    "nuxt": "4.4.8"
    "nuxt-viewport": "2.6.0"
    "pinia": 4.0.3
    "@pinia/nuxt": "1.0.2"

  ui:
    "@nuxt/fonts": 0.14.0
    "@nuxt/icon": 2.5.0
    "@nuxt/ui": 4.10.0
    "@tailwindcss/vite": 4.3.3
    "tailwindcss": 4.3.3

minimumReleaseAgeExclude:
  - '@pinia/nuxt@1.0.2'
  - pinia@4.0.3
