# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
    # Schedule updates (each hour)
    schedule:
        - cron: 0 0 * * *
        # Lines below let you run workflow manually and on each commit
    workflow_dispatch:
    push: { branches: ["master", "main"] }

jobs:
    github-metrics:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        environment:
            name: "production"
        steps:
            - name: "Checkout Repository"
              uses: actions/checkout@v7
            - name: "Get Bot"
              id: "get-bot"
              uses: raven-actions/bot-details@v1
            - name: "Delete Original"
              run: |
                  rm -f github-metrics.svg
                  if [ -f "github-metrics.svg" ]; then
                    echo "\033[1;91mFailed to delete \033[1;97mgithub-metrics.svg\033[0m"
                  else
                    echo "\033[1;92mSuccessfully deleted \033[1;97mgithub-metrics.svg\033[0m"
                  fi
                  git config --global user.name "${{ steps.get-bot.outputs.name }}"
                  git config --global user.email "${{ steps.get-bot.outputs.email }}"
                  git add github-metrics.svg
                  git commit -m "Deleted github-metrics.svg"
                  git push
            - name: "Fetch Metrics"
              uses: lowlighter/metrics@v3.34
              with:
                  # Your GitHub token
                  # The following scopes are required:
                  #  - public_access (default scope)
                  # The following additional scopes may be required:
                  #  - read:org      (for organization related metrics)
                  #  - read:user     (for user related data)
                  #  - read:packages (for some packages related data)
                  #  - repo          (optional, if you want to include private repositories)
                  token: ${{ secrets.METRICS_TOKEN }}

                  # Options
                  user: JetVolcano
                  template: classic
                  base: header, activity, community, repositories
                  config_display: regular
                  config_octicon: yes
                  config_timezone: America/Los_Angeles
                  config_padding: 0, 8 + 11%
                  plugin_isocalendar: yes
                  plugin_isocalendar_duration: 2
                  plugin_followup: yes
                  plugin_followup_archived: yes
                  plugin_followup_indepth: yes
                  plugin_followup_sections: repositories
                  plugin_languages: yes
                  plugin_languages_analysis_timeout: 15
                  plugin_languages_analysis_timeout_repositories: 10
                  plugin_languages_categories: markup, programming
                  plugin_languages_colors: github
                  plugin_languages_details: percentage
                  plugin_languages_limit: 8
                  plugin_languages_other: yes
                  plugin_languages_recent_categories: markup, programming
                  plugin_languages_recent_days: 14
                  plugin_languages_recent_load: 300
                  plugin_languages_sections: most-used
                  plugin_languages_threshold: 0%
