# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  schedule:
    - cron: 0 0 * * *
    # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master", "main"] }

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment:
      name: "production"
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v7
      - name: "Get Bot"
        id: "get-bot"
        uses: raven-actions/bot-details@v1
      - name: "Delete Original"
        run: |
          rm -f public/metrics.svg
          if [ -f "public/metrics.svg" ]; then
            echo -e "\033[1;91mFailed to delete \033[1;97mmetrics.svg\033[0m"
          else
            echo -e "\033[1;92mSuccessfully deleted \033[1;97mmetrics.svg\033[0m"
          fi
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name "${{ steps.get-bot.outputs.name }}"
            git config --global user.email "${{ steps.get-bot.outputs.email }}"
            git add public/metrics.svg
            git commit -m "Deleted metrics.svg"
            git push
          fi
      - name: "Fetch Metrics"
        uses: lowlighter/metrics@v3.34
        with:
          filename: public/metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: JetVolcano
          template: classic
          base: header, activity, community, repositories
          config_display: regular
          config_octicon: yes
          config_timezone: America/Los_Angeles
          config_padding: 0, 8 + 11%
          plugin_isocalendar: yes
          plugin_isocalendar_duration: 2
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_indepth: yes
          plugin_followup_sections: repositories
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 10
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: percentage
          plugin_languages_limit: 8
          plugin_languages_other: yes
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
